# Generated by Django 3.1.1 on 2020-09-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='precion',
            new_name='precio',
        ),
    ]
